on:
  push

jobs:
  build-and-publish-docker:
    name: Build and publish testing environment docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag name
        id: vars
        run: |
            if [ ${GITHUB_REF#refs/*/} -eq master ]
            then
              echo ::set-output name=tag::latest
            else
              echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            fi
      - name: Check tag name
        run: echo ${{ steps.vars.outputs.tag }}
      - name: Make cache folder
        run: mkdir ~/cache
      - name: Cache Dockerfile
        id: cache-docker
        uses: actions/cache@v2
        with:
          path: ~/cache/Dockerfile
          key: ${{ runner.os }}-Dockerfile-${{ steps.vars.outputs.tag}}-${{ hashFiles('Dockerfile') }}
      - name: touch ~/cache/Dockerfile
        run: touch ~/cache/Dockerfile
      - name: compare Dockerfile with cache
        id: diff
        run: |
            if diff Dockerfile ~/cache/Dockerfile > /dev/null; then
                echo ::set-output name=changed::no
            else
                echo ::set-output name=changed::yes
            fi
      - name: Copy Dockerfile to ~/cache/Dockerfile
        run: cp Dockerfile ~/cache/Dockerfile

      - name: Build and push testing Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mscroggs/bempp-cl-and-dolfinx
          tags: ${{ steps.vars.outputs.tag }}
          target: dolfinx-and-bempp
          cache_froms: mscroggs/bempp-cl-and-dolfinx:${{ steps.vars.outputs.tag }}
        if: steps.diff.outputs.changed == 'yes'
